spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres_bdp:5432/bdp_credit_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bdp_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Bdp2024Secure!}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
